# Generated by Django 2.1.7 on 2019-02-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20190226_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
